core/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth.views import login,logout
from . import views

app_name = 'core'

urlpatterns = [
    #homepage
    url(r'^$',views.index,name='index'),
    #profile_realted
    url(r'^register/$',views.register,name='reg'),
    url(r'accounts/profile/$',views.account,name='account'),
    url(r'login/$',login,{'template_name':'core/login.html'},name='login'),
    url(r'logout/$',logout,{'template_name':'core/logout.html'},name='logout'),
    #details_of_courses&proffesor
    url(r'^course/(?P<course_id>[0-9]+)$',views.detailc,name='detailc'),
    url(r'^prof/(?P<proffesor_id>[0-9]+)$',views.detailp,name='detailp'),
    #write review
    url(r'^course/(?P<course_id>[0-9]+)/re$',views.bleh,name='noice'),
    url(r'^prof/(?P<proffesor_id>[0-9]+)/re$',views.blep,name='noicep'),
    #helper_urls
    url(r'^course/(?P<course_id>[0-9]+)/r$',views.reviewc,name='reviewc'),
    url(r'^prof/(?P<proffesor_id>[0-9]+)/r$',views.reviewp,name='reviewp'),
]

ratemyprof/urls.py
from django.conf.urls import url
from django.contrib import admin
from ratemyprof.views import hello_world
from ratemyprof.views import root_page,random_number,redirec
from django.conf.urls import include
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^lol/$',hello_world),
    url(r'^$',root_page),
    url(r'^accounts/profile/$',redirec),
    url(r'^random/(\d+)/$',random_number),
    url(r'^ratemyprof/',include('core.urls')),
]

core/models.py
from django.db import models
import datetime
from django.utils import timezone
from django.contrib.auth.models import User
class Professor(models.Model):
    Name = models.CharField(max_length=200)
    #image = models.ImageField(upload_to='uploads/', height_field=None, width_field=None, max_length=100,defaul)
    def __str__(self):
        return self.Name
        
class Course(models.Model):
    Name = models.CharField(max_length=200) 
    Course_id = models.CharField(max_length=200,default="MTLXXX")
    def __str__(self):
        return self.Course_id

class PReview(models.Model):
    question=models.ForeignKey(Professor,on_delete=models.CASCADE)
    review_text = models.CharField(max_length=200)
    is_ano = models.BooleanField(default=False)
    author = models.ForeignKey(User,on_delete=models.CASCADE,default=None)
    pub_date = models.DateTimeField(auto_now="True" 'date published')

class CReview(models.Model):
    question=models.ForeignKey(Course,on_delete=models.CASCADE)
    review_text = models.CharField(max_length=200)
    is_ano = models.BooleanField(default=False)
    author = models.ForeignKey(User,on_delete=models.CASCADE,default=None)
    pub_date = models.DateTimeField(auto_now="True" 'date published')  

class UserProfile(models.Model):
    user = models.OneToOneField(User)
    bio = models.CharField(max_length=300)

core/forms.py
from django import forms

core/views.py
from django.shortcuts import render
import time
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import get_object_or_404
from .models import CReview,PReview,Course,Professor
from django.contrib.auth.forms import UserCreationForm

#https://www.ling.upenn.edu/courses/Spring_2003/ling538/Lecnotes/ADfn1.htm
#https://www.d.umn.edu/~gshute/logic/barrel-shifter.xhtml
#A common usage of a barrel shifter is in the hardware implementation of floating-point arithmetic. For a floating-point add or subtract operation, the significands of the two numbers must be aligned, which requires shifting the smaller number to the right, increasing its exponent, until it matches the exponent of the larger number. This is done by subtracting the exponents and using the barrel shifter to shift the smaller number to the right by the difference, in one cycle. If a simple shifter were used, shifting by n bit positions would require n clock cycles.
#A Java applet which simulates a barrel-shifter - https://tams.informatik.uni-hamburg.de/applets/hades/webdemos/10-gates/60-barrel/shifter8.html
#https://iitd-plos.github.io/col718/ref/arm-instructionset.pdf
#https://developer.arm.com/docs/ddi0210/c/introduction/instruction-set-summary/arm-instruction-summary
#https://e-vent.mit.edu/

def account(request):
    return render(request, 'core/profile.html',{'user':request.user})

def bleh(request,course_id):
    i = get_object_or_404(Course,pk=course_id)
    if request.user.is_authenticated():
        return render(request, 'core/review.html',{'Course':i,'user':request.user})
    else:
        return HttpResponseRedirect(reverse('core:login'))    

def blep(request,proffesor_id):
    i = get_object_or_404(Professor,pk=proffesor_id)
    if request.user.is_authenticated():
        return render(request, 'core/reviewp.html',{'Professor':i,'user':request.user})
    else:
        return HttpResponseRedirect(reverse('core:login'))    
    

def index(request):
    course_list=Course.objects.order_by('Name')
    prof_list=Professor.objects.order_by('Name')
    context = {
        'course_list' : course_list,
        'prof_list' : prof_list,
        'user' : request.user
    }
    return render(request,'core/index.html',context)

def detailc(request,course_id):
    i = get_object_or_404(Course,pk=course_id)
    return render(request, 'core/detail.html',{'dic':i,'user':request.user})

def detailp(request,proffesor_id):
    i = get_object_or_404(Professor,pk=proffesor_id)
    return render(request, 'core/detailp.html',{'dic':i,'user':request.user})

def reviewc(request, course_id):
    reviewt = request.POST.get( 're1', None )
    y = request.POST.get( 'ano', None )
    if y=="anonymous":
        temp = CReview(question=Course.objects.get(pk=course_id),review_text=reviewt,author=request.user,is_ano=True)
    else:
        temp = CReview(question=Course.objects.get(pk=course_id),review_text=reviewt,author=request.user,is_ano=False)    
    temp.save()
    return HttpResponseRedirect(reverse('core:detailc',args=course_id))

def reviewp(request, proffesor_id):
    reviewt = request.POST.get( 're1', None )
    y = request.POST.get( 'ano', None )
    if y=="anonymous":
        temp = PReview(question=Professor.objects.get(pk=proffesor_id),review_text=reviewt,author=request.user,is_ano=True)
    else:
        temp = PReview(question=Professor.objects.get(pk=proffesor_id),review_text=reviewt,author=request.user,is_ano=False) 
    temp.save()
    return HttpResponseRedirect(reverse('core:detailp',args=proffesor_id))


def register(request):
    if request.method=='POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('core:index'))
    else:
        form = UserCreationForm()        
        args={'form':form}
        return render(request,'core/reg.html',args)

ratemyprof/views.py
from django.http import HttpResponse,HttpResponsePermanentRedirect,HttpResponseRedirect
from django.urls import reverse
import random
def hello_world(request):
    return HttpResponse("Hello World")

def root_page(request):
    return HttpResponse("Home Page")

def redirec(request):
    return HttpResponseRedirect(reverse('core:account'))

def random_number(request,max_rand=100):
    random_number = random.randrange(0,int(max_rand))

    msg = "Random number Between 0 and %s : %d" %(max_rand,random_number)

    return HttpResponse(msg)

core/templates/core/detail.html
<a href={% url 'core:index' %}>Home</a>
{% if user.is_authenticated %}
    <a href={% url 'core:logout' %}>logout</a>
    <a href={% url 'core:account' %}>Profile</a>
{% else %}
    <a href={% url 'core:login' %}>Login</a>
{% endif %} 
<h1>{{dic.Name}}</h1>
<ul>
    {% for cre in dic.creview_set.all  %}
    <li>
        {{cre.review_text}}.
        <br> Author :
        {% if cre.is_ano %}
            Anonymous
        {% else %}
            {{cre.author.username}}
        {% endif %}        
    </li>
    {% endfor %}
</ul>
<a href={% url 'core:noice' dic.pk %}>Add a review</a>

core/templates/core/detailp.html
<a href={% url 'core:index' %}>Home</a>
{% if user.is_authenticated %}
    <a href={% url 'core:logout' %}>Logout</a>
    <a href={% url 'core:account' %}>Profile</a>
{% else %}
    <a href={% url 'core:login' %}>Login</a>
{% endif %} 
<h1>{{dic.Name}}</h1>
<ul>
    {% for cre in dic.preview_set.all  %}
    <li>
        {{cre.review_text}}.
        <br> Author :
        {% if cre.is_ano %}
            Anonymous
        {% else %}
            {{cre.author.username}}
        {% endif %}    
    </li>
    {% endfor %}
</ul>
<a href={% url 'core:noicep' dic.pk %}>Add a review</a>

core/templates/core/index.html
{% if user.is_authenticated %}
    <a href={% url 'core:logout' %}>Logout</a>
    <a href={% url 'core:account' %}>Profile</a>
{% else %}
    <a href={% url 'core:login' %}>Login</a>
{% endif %}       

<h1>Courses</h1>
{% if course_list %}
    <ul>
            {% for i in course_list %}
                <li>
                    <a href="{% url 'core:detailc' i.id %}">{{i.Name}}</a>
                </li>
            {% endfor %}        
    </ul>            
{% else %}
    <p> No Course Found</p>  
{% endif %}

<h1>Professor</h1>
{% if prof_list %}
    <ul>
            {% for i in prof_list %}
                <li>
                    <a href="{% url 'core:detailp' i.id %}">{{i.Name}}</a>
                </li>
            {% endfor %}        
    </ul>            
{% else %}
    <p> No Professor Found</p>  
{% endif %}

core/templates/core/login.html
<a href={% url 'core:index' %}>Home</a>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" name="button">Login</button>
</form>
<a href={% url 'core:reg' %}>Register</a>

core/templates/core/logout.html
You have logged out
<a href={% url 'core:index' %}>Home</a>

core/templates/core/profile.html
{% if user.is_authenticated %}
    <a href={% url 'core:logout' %}>Logout</a>
    <a href={% url 'core:index' %}>Home</a>
{% else %}
    <a href={% url 'core:login' %}>Login</a>
{% endif %} 
<h1>{{user.username}}</h1>
<ul>
    {% for cre in user.preview_set.all  %}
    <li>
        {{cre.question.Name}}<br>
        {{cre.review_text}}
    </li>
    {% endfor %}
    {% for cre in user.creview_set.all  %}
    <li>
        {{cre.question.Name}}<br>
        {{cre.review_text}}
    </li>
    {% endfor %}
</ul>

core/templates/core/reg.html
<a href={% url 'core:index' %}>Home</a>
<form method="POST">
    {% csrf_token %}
    {{ form.as_ul }}
    <button type="submit">Create Account
    </button>
</form>

core/templates/core/review.html
<a href={% url 'core:index' %}>Home</a>
<h1>{{Course.Name}}</h1>
{% if error_message %}
<p><strong>Error Message</strong>></p>
{% endif %}

<form action="{% url 'core:reviewc' Course.pk %}" method="post">
    {% csrf_token %}
    <input type="text" name = "re1"/>
    <input type="checkbox" id="ano" name="ano" value="anonymous">
    <label for="anonymous">Post Anonymously </label><br>
    <input type = "submit" value="Submit" />
</form>    

core/templates/core/reviewp.html
<a href={% url 'core:index' %}>Home</a>
<h1>{{Professor.Name}}</h1>
{% if error_message %}
<p><strong>Error Message</strong>></p>
{% endif %}

<form action="{% url 'core:reviewp' Professor.pk %}" method="post">
    {% csrf_token %}
    <input type="text" name = "re1"/>
    <input type = "submit" value="Submit" />
    <input type="checkbox" id="ano" name="ano" value="anonymous">
    <label for="anonymous">Post Anonymously </label><br>
</form>    

    